baseURL: "https://nirgf.github.io" 
title: Nir Goldfriend
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 2
        - name: Work in Progress
          url: wp/
          weight: 3
        - name: Home
          url: /
          weight: 1
         # url: data/
          #weight: 3 
        #- name: Readings
         # url: readings/
          #weight: 4

params:
    description: "I am a physicist in background and engineer in practice."
    author: Nir
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nir Goldfriend
          subtitle: "I am a physicist in background and engineer in practice. Currently I'm at Apple, working on cameras and depth sensors architecture. Before that, I work on photoacoustic imaging which is an emerging technology combining optics, acoustic, singal processing and computational optimzation."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Nir
          buttons:
            - name: Research
              url: papers/
            - name: Work in Progress
              url: wp/
            #- name: Data
             # url: data/
            #- name: Readings
             # url: readings/
            #- name: Tags
             # url: tags/
            #- name: Archive
             # url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:nircko@yahoo.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/nir-goldfriend-a556b6176/
        - name: GitHub
          url: https://github.com/nircko
        # - name: Twitter
          # url: https://www.linkedin.com/in/nir-goldfriend-a556b6176

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Nir Goldfriend"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
